version: "3.4"

services:
  phonebook_test_api:
    build:
      context: .
      dockerfile: Dockerfile
      target: phonebook_test_nginx
    container_name: phonebook_test_api
    ports:
      - ${NGINX_HOST_PORT}:80
    links:
      - phonebook_test_php
    volumes:
      - ./api:/var/www/phonebook_test
    depends_on:
      - phonebook_test_php
    networks:
      - api

  phonebook_test_php:
    build:
      context: .
      dockerfile: Dockerfile
      target: phonebook_test_php
    container_name: phonebook_test_php
    volumes:
      - ./api:/var/www/phonebook_test
    environment:
      DB_HOST: ${DB_EXTERNAL_HOST}
      DB_PORT: ${DB_EXTERNAL_PORT}
      DB_USERNAME: ${DB_EXTERNAL_USERNAME}
      DB_DATABASE: ${DB_EXTERNAL_DATABASE}
      DB_PASSWORD: ${DB_EXTERNAL_PASSWORD}
    networks:
      - api

networks:
  api:
    driver: bridge